version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Web
      - "4001:4001"  # API
    environment:
      # API Configuration
      - NODE_ENV=production
      - API_PORT=4001
      - WEB_PORT=4000
      - CORS_ORIGINS=http://localhost:4000
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - ENABLE_AUTH=${ENABLE_AUTH:-false}
      
      # Web Configuration  
      - NEXT_PUBLIC_API_URL=http://localhost:4001
      - NEXT_PUBLIC_WEB_URL=http://localhost:4000
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    volumes:
      # Mount for development (optional - remove for pure production testing)
      - ./.env:/app/.env:ro
    healthcheck:
      test: |
        wget --no-verbose --tries=1 --spider http://localhost:4001/api/health && 
        wget --no-verbose --tries=1 --spider http://localhost:4000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped