name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  # Variables mínimas para builds
  NEXT_PUBLIC_API_URL: http://localhost:4001

jobs:
  lint:
    name: Lint (web + api)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint web
        run: pnpm --filter @que-hacer-en/web run lint

      - name: Lint api
        run: pnpm --filter @que-hacer-en/api run lint

  test_api:
    name: Unit Tests (api)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test api (coverage)
        run: pnpm --filter @que-hacer-en/api run test:coverage

      - name: Upload coverage artifact (api)
        uses: actions/upload-artifact@v4
        with:
          name: api-coverage
          path: packages/api/coverage
          if-no-files-found: error
          retention-days: 7

  build:
    name: Build (web + api)
    runs-on: ubuntu-latest
    needs: [lint, test_api]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build api
        run: pnpm --filter @que-hacer-en/api run build

      - name: Build web
        run: pnpm --filter @que-hacer-en/web run build

  e2e:
    name: E2E (Playwright)
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm --filter @que-hacer-en/web exec playwright install --with-deps

      - name: Build api
        run: pnpm --filter @que-hacer-en/api run build

      - name: Build web
        env:
          NEXT_PUBLIC_API_URL: http://localhost:4001
        run: pnpm --filter @que-hacer-en/web run build

      - name: Start API (prod build)
        run: pnpm --filter @que-hacer-en/api run start &

      - name: Start Web (prod build)
        env:
          NEXT_PUBLIC_API_URL: http://localhost:4001
          CI: true
          E2E: true
        run: pnpm --filter @que-hacer-en/web exec next start -p 4000 &

      - name: Wait for services
        run: |
          npx -y wait-on --timeout 180000 --httpTimeout 10000 http://localhost:4001/api/health http://localhost:4000

      - name: Run E2E tests (Chromium/Firefox/WebKit)
        env:
          WEB_BASE_URL: http://localhost:4000
          CI: true
        run: pnpm --filter @que-hacer-en/web run e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: packages/web/playwright-report
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: packages/web/test-results
          if-no-files-found: ignore
          retention-days: 7


