name: Trigger auto deployment for que-hacer-en-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/que-hacer-en-app-AutoDeployTrigger-e9a324a1-599a-401f-ab05-958d4ae77bf9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.QUEHACERENAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.QUEHACERENAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.QUEHACERENAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/.Dockerfile
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.QUEHACERENAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.QUEHACERENAPP_REGISTRY_PASSWORD }}
          containerAppName: que-hacer-en-app
          resourceGroup: que-hacer-en-rg
          imageToBuild: ghcr.io/que-hacer-en-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


